default_language_version:
    python: python3.10

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-ast
      - id: check-toml
      - id: check-yaml
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 5.9.3
    hooks:
      - id: isort
  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear==21.9.2
          - flake8-comprehensions==3.6.1
          - flake8-deprecated==1.3
          - flake8-docstrings==1.6.0
          - flake8-implicit-str-concat==0.2.0
          - flake8-keyword-arguments==0.1.0
          - flake8-print==4.0.0
          - flake8-sfs==0.0.3
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        additional_dependencies:
          - types-PyYAML==5.4.10
          - types-setuptools==57.4.0
          - types-requests==2.25.9
        exclude: tests
